// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ToDoList21.Data;

namespace ToDoList21.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20220622104945_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ToDoList21.Models.Problem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<string>("Executors");

                    b.Property<int?>("FactTime");

                    b.Property<DateTime?>("FinishDate");

                    b.Property<int>("PlannedComplexityTime");

                    b.Property<int?>("ProblemId");

                    b.Property<DateTime>("StartDate");

                    b.Property<int>("Status");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.HasIndex("ProblemId");

                    b.ToTable("ProblemSet");
                });

            modelBuilder.Entity("ToDoList21.Models.Problem", b =>
                {
                    b.HasOne("ToDoList21.Models.Problem")
                        .WithMany("SubProblems")
                        .HasForeignKey("ProblemId");
                });
#pragma warning restore 612, 618
        }
    }
}
